import type { Metadata } from "next";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { geistSans } from "@/lib/fonts";
import { AppSidebar } from "@/components/appSidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.className} h-full antialiased`}>
            <body className="w-screen">
                <SidebarProvider>
                    <AppSidebar />
                    <main className="flex w-full flex-row items-start justify-start">
                        <SidebarTrigger className="sticky top-0" />
                        <div className="flex w-full">{children}</div>
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
